server:
  port: 8081

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: Thinux_Demo
  auth-server-url: http://localhost:8080
  resource: thinux-demo-rest-api
  public-client: true
  bearer-only: true